### PR TITLE
Redacting political affilliations from mails

### PR DESCRIPTION
**Pull request by tdg**
NOT FOR PUBLICATION YET
REVIEW BEFORE LAUNCH

Redacts political affiliations from mails 

They are correspondingly colourless, so let’s decide whether to publish these changes before launch

### CODE REVIEW

**Comment by aspiers** [comment]
@tdg So the decision was to scrap this, or what?

**Comment by aspiers** [comment]
[**@aspiers**](https://github.com/aspiers) commented on [December 2, 2019 10:43 PM](https://github.com/swapmyvote/swapmyvote/pull/224#issuecomment-560526490 "2019-12-02T18:43:15Z - Replied by Github Reply Comments"):
> @tdg So the decision was to scrap this, or what?

Still need your answer on this!

**Comment by tdg** [comment]
Scrap for now yes. Keep copy to hand in cases needed it hopefully won’t be

**Comment by aspiers** [comment]
Rebased against latest `master`.

**Comment by aspiers** [comment]
Resurrecting for BE2021.  @tdg @baob Would greatly appreciate very careful reviews on this one.  You can focus on the middle commit - the other two are trivial.

**Comment by baob** [comment]
Not really sure why we're doing this, are we anticipating emails being intercepted ?

Anyway, happy with the code.

**Review by baob — APPROVED** [review]

**Pull request merged**
