### PR TITLE
close off the route to empty constituencies via user/constituencies/edit (#622)

### LINKED ISSUE #622: Bug: user asked to select constituency on creating swap, but allowed to leave blank
The scenario is
- user registers without specifying constituency
- user is offered swaps (both constituencies, since we don't know where they are)
- user chooses a potential swap
- app knows that constituency is missing and asks user to choose (check introduced in #289) 
- user hits save WITHOUT CHOOSING constituency and the APP ALLOWS IT.

Discovered while investigating #621

### PR DESCRIPTION
**Pull request by baob**
Should close #622

Please can someone other than me try to prove this works ? @tdg @aspiers ?

Register as a new user, and see if you can get to a point of seeing
swaps without setting your constituency ?

I don't think it can be done any more, as of this fix

### CODE REVIEW

**Comment by tdg** [comment]
image

I got this error message at https://swapmyvote-pr-633.herokuapp.com/users 

I was using one of my principal email addresses (@m……….tv) which might exist already in the database?

**Comment by tdg** [comment]
Replicated error with two other email addresses, one of which was definitely unique

**Comment by baob** [comment]
Ohhh ... totally forgot, anything that uses email (including signing up as a new user, which I asked you to do) fails on the review apps. There's a GitHub issue for it.

I'd better think of another plan for testing.

**Comment by baob** [comment]
@tdg and @aspiers could you please test on your own, local apps if possible, by checking out the branch constituency-is-not-optional .

Testing on review apps will be hard in this case due to the problem raised in #618 .

**Review by tdg — APPROVED** [review]
Every time I try to save edit user without a constituency it takes me to that page, and the error message works there. It seems like the only way to leave it blank would be to ignore what we're asking and simply leave it black, so it works as increasing likelihood of user providing the constituency.

The only way I can imagine ensuring every user specifies constituency would be to do so on first sign up perhaps as part of the initial action flow

**Comment by baob** [comment]
> The only way I can imagine ensuring every user specifies constituency would be to do so on first sign up perhaps as part of the initial action flow

That's pretty much what I was saying in https://github.com/swapmyvote/swapmyvote/issues/625

**Pull request merged**
