### PR TITLE
tweak copy on swaps page

### PR DESCRIPTION
**Pull request by aspiers**

### CODE REVIEW

**Review by tdg — COMMENTED** [review]
I actually like the two levels of subjectivity – one for polls, one for elections

**Comment by baob** [comment]
While you're in there the "which is" text is problematic. Works fine for singular party names ("labour") less so for plurals ("conservatives", "liberal democrats").

Extra points if you can squeeze is a simple fix  :) ... otherwise merge as is and tackle this elsewhere.

**Comment by tdg** [comment]
'who are'

**Comment by tdg** [comment]
> I actually like the two levels of subjectivity – one for polls, one for elections

Also, I like how _human_ it sounds - we could do with more of that sense in our copy, which tends to the dry (I should know!)

**Comment by aspiers** [comment]
Dropped the commit removing "Looks like".

**Review by baob — APPROVED** [review]

**Pull request merged**
