### PR TITLE
Test: users_controller.rb

### PR DESCRIPTION
**Pull request by EmersonManabuAraki**
users_controller.rb test coverage up to 86.67%

### CODE REVIEW

**Comment by aspiers** [comment]
@cla-bot check

**Comment by aspiers** [comment]
Thanks a lot @EmersonManabuAraki for signing the CLA however you still need to follow the instructions above regarding matching the email in the commit message with an email which GitHub recognises.

**Comment by EmersonManabuAraki** [comment]
I just configured the email

**Comment by aspiers** [comment]
Fantastic, thanks!

**Pull request merged**
