### PR TITLE
configure haml_lint and guard-haml_lint (#141)

### LINKED ISSUE #141: add HAML linting
We need HAML linting locally, just like we have rubocop and scss_lint.  @aspiers already has the changes for this, but it also requires a ton of fixes for HAML lint.

- https://github.com/sds/haml-lint/blob/master/lib/haml_lint/linter/README.md

### PR DESCRIPTION
**Pull request by aspiers**
Identical setup to scss_lint.

Also add a new 'lint' task to Rake which runs all three linters.

Will fix #141 when all the linting issues are addressed.

### CODE REVIEW

**Comment by aspiers** [comment]
Posting this before it gets lost in my local repo, but I recommend we avoid this until M4 because it will cause merge conflicts with other PRs and slow down development.

**Review by stevebaxter — DISMISSED** [review]
LGTM from a JS POV, not much change there though!

**Comment by baob** [comment]
There's an updated branch at https://github.com/baob/swapmyvote/pull/new/haml-lint  but it produces an awful lot of warnings ... and I suspect they will need manual changes, not automated corrections like rubocop.

**Comment by aspiers** [comment]
@baob Take a look at this :-)

**Comment by aspiers** [comment]
Rebased

**Pull request closed without merging**
