### PR TITLE
issue 797 fix password required

### PR DESCRIPTION
**Pull request by baob**
Tries to address issue #797

@steve baxter I didn't use your solution, I found problems with it, see commit messages.

I think this does what you want though, please check it out and see if the bug is fixed.

- add password to user factory for tests
- change the harmful override, false/true both bad
- now suppress the 2 failing tests, not relevant now

### CODE REVIEW

**Review by stevebaxter — APPROVED** [review]
LGTM! I guess does Devise automatically not require a valid password when creating users in tests?

**Comment by baob** [comment]
The key thing it getting it all to behave sensibly was to provide a password with every user created for testing. Letting devise take care of the value of that function then made for sensible behaviour when updating the user without updating the password.

BUT PLEASE TEST. I only did minimal testing based you saying the value of that function needed to change.

**Comment by stevebaxter** [comment]
Can you update your repo from swapmyvote/master please? I can't run it on my Mac without the upstream changes.

**Comment by baob** [comment]
I've done an update from swapmyvote master ... no change.
```
$ git pull --rebase swapmyvote master
From github.com:swapmyvote/swapmyvote
 * branch              master     -> FETCH_HEAD
Current branch issue-797-fix-password-required is up to date.
```
This is the master commit I see
```
$ git log -n1 swapmyvote/master
commit 28c83a8ac50392b0cea0c68ce537a9cb52ded908 (swapmyvote/master, swapmyvote/HEAD, master)
Merge: 01099782 31f78f45
Author: Adam Spiers <swapmyvote@adamspiers.org>
Date:   Tue Jun 11 23:35:22 2024 +0100

    Merge pull request #799 from baob/issue-794-party-colours-in-poll-chart
```

**Review by aspiers — APPROVED** [review]

**Pull request merged**
