### PR TITLE
issue-153-donate

### PR DESCRIPTION
**Pull request by fkorning**
first release (finally).
new _titler.html.haml layout
new titler.scss stylesheet
comments

### CODE REVIEW

**Comment by fkorning** [comment]
@tdg quick questions before we integrate this. 
 (1) what colour do you want the button (grey or magenta) ? 
 (2) do you want the login to also be a buton instead of a link?

**Comment by fkorning** [comment]
image

**Comment by fkorning** [comment]
optional login-button.
https://github.com/fkorning/swapmyvote/tree/login-button

**Comment by fkorning** [comment]
with optional login button (see "login-button" branch above)

image

**Comment by tdg** [comment]
https://github.com/swapmyvote/swapmyvote/pull/313#issuecomment-562943072

I think I like it best with just the one button like this. Nice work @fkorning!

**Comment by fkorning** [comment]
thanks. very belated modest contribution. apologies, learning curve is steep for a boring backend guy.

**Comment by tdg** [comment]
> thanks. very belated modest contribution. apologies, learning curve is steep for a boring backend guy.

Very much appreciated - and hope that you can put all that learning to more good use :)

**Pull request closed without merging**
