### PR TITLE
stt update to ge data from by election data

### PR DESCRIPTION
**Pull request by baob**
Main steps

- new STT csv
- update advice key ( (extra columns in the CSV)
- Only allow through party names

### CODE REVIEW

**Comment by aspiers** [comment]
@baob This one is based on #757 which is still marked draft, should we mark that as ready and review, or close it and just merge this one?

**Comment by aspiers** [comment]
On phone now but when I checked earlier this pr was just a single commit on top of the draft one?

**Comment by baob** [comment]
> I.e impossible to merge this one without also merging the other

I checked again ... THIS one has 3 commits and is ready to merge. PR #757 is draft and has one more commit on top of this one (4 in total) ... it's draft because needs more work before everyone is happy with the "heart" solution.

**Comment by aspiers** [comment]
My bad, got them mixed up somehow, probably because this PR has the higher number so assumed the older one couldn't be based on top of it.

**Review by aspiers — APPROVED** [review]

**Pull request merged**
