### PR TITLE
upsert all rows of some seed tables in one go

### PR DESCRIPTION
**Pull request by aspiers**
This can save several minutes in the `db:seed` part of `db:setup`.

Partially addresses #675.

### CODE REVIEW

**Comment by aspiers** [comment]
@baob This makes seeding stages near instant.

**Comment by aspiers** [comment]
I had a look at trying to do the same for STT recommendations, but it wasn't simple because it relies on `update_parties` in the model and also can do deletes in some scenarios.

**Comment by aspiers** [comment]
But also @baob I see that `Recommendation.update_parties` causes three `SELECT` statements for each insert, which makes it SUPER slow.

**Comment by baob** [comment]
Your upsert code looks good, but the whole seeding process looks broken, almost certainly by the recent password change for users (my change). Are you seeing errors like this on seeding users ? (db:seed:development:users)

> User robert.2-4-1@example.com not created: ["Password can't be blank"]

**Comment by aspiers** [comment]
Yes I am seeing that too.  We need to set a password for test users.

**Comment by baob** [comment]
I've pushed a fixed branch to my repo, but my test setup is messed up, so I can't be sure wether anything is broken. @aspiers could you please cherry pick that fix into your branch ?  My branch has the same name.

**Comment by aspiers** [comment]
@baob Rebased, cherry-picked, and added another commit I forgot to push before.

**Comment by baob** [comment]
Tests still broken for me but I guess they're passing for you and CI.

**Pull request merged**
