### PR TITLE
fix broken PollsHelper spec (#8)

### PR DESCRIPTION
**Pull request by baob**

### CODE REVIEW

**Comment by aspiers** [comment]
Looks fine but this spec already passes for me without this PR.  What breakage are you seeing?

**Comment by baob** [comment]
```
  1) PollsHelper#poll_data_for is expected not to raise Exception
     Failure/Error: specify { expect { helper.poll_data_for(constituency) }.not_to raise_error }

       expected no Exception, got #<NoMethodError: undefined method `name' for nil:NilClass> with backtrace:
         # ./app/helpers/polls_helper.rb:5:in `block in poll_data_for'
         # ./app/helpers/polls_helper.rb:4:in `each'
         # ./app/helpers/polls_helper.rb:4:in `poll_data_for'
         # ./spec/helpers/polls_helper_spec.rb:7:in `block (4 levels) in <top (required)>'
         # ./spec/helpers/polls_helper_spec.rb:7:in `block (3 levels) in <top (required)>'
     # ./spec/helpers/polls_helper_spec.rb:7:in `block (3 levels) in <top (required)>'
```

**Comment by baob** [comment]
I wonder if you have data in your test DB that's allowing the test to pass ... test database not being cleaned ? I will have a look at my test db.

**Comment by baob** [comment]
Alright. Findings:
1) Test DB is not empty on my machine. So it looks like rspec is not clearing DB (i thought the default setup did that) so I may need to implement https://github.com/swapmyvote/swapmyvote/issues/53
2) If I truncate a few tables in the test DB, I also get the test to pass without the fix ... so no need to merge at present

**Comment by aspiers** [comment]
I did run `db:setup` in my `test` environment a while back so I guess that would explain it.

**Comment by aspiers** [comment]
... but I think it would make more sense to use factory_bot here anyway, right?

**Comment by baob** [comment]
Problem hasn't come back ... must have been data.

**Pull request closed without merging**
