### PR TITLE
Modal fix

### LINKED ISSUE #484: Login button in closed-wind-down is broken
`onclick="$('#js-login-modal').modal(); return false"` results in:

```
(index):68 Uncaught TypeError: $(...).modal is not a function
    at HTMLAnchorElement.onclick ((index):68)
```

This is super weird because it works fine in other modes, and `.modal()` is defined by bootstrap.

### PR DESCRIPTION
**Pull request by JFernando122**
Fixing link so the log-in modal is properly displayed (Fixes #484 )

### CODE REVIEW

**Review by aspiers — APPROVED** [review]
Fantastic, thanks!  So why was this working in other modes but not for `closed-and-voting`?

**Comment by JFernando122** [comment]
Not exactly sure as of why would work in some places and in others don't, what i found in [Stackoverflow](https://stackoverflow.com/questions/27064176/typeerror-modal-is-not-a-function-with-bootstrap-modal) was that when there are multiple jquery instances or bootstrap was called before jquery it won't work.

**Comment by aspiers** [comment]
Strange, well anyway the fix is hugely appreciated even though I don't really understand it! :laughing:

**Comment by aspiers** [comment]
BTW how did you find this project? :-)

**Comment by JFernando122** [comment]
By searching for the "help wanted" label :)

**Comment by aspiers** [comment]
Amazing, it actually works! Thanks so much again 😁

**Pull request merged**
